guillaume_crud:
    resource: "@GuillaumeCRUDBundle/Resources/config/routing.yml"
    prefix:   /CRUD

guillaume_twig:
    resource: "@GuillaumeTwigBundle/Resources/config/routing.yml"
    prefix:   /GuillaumeTwig

guillaume_racine:
    resource: "@GuillaumeRacineBundle/Resources/config/routing.yml"
    prefix:   /

